import { getUserId } from '@/lib/stripe/auth'
import { stripe } from '@/lib/stripe/client'
import { getOrCreateCustomerId } from '@/lib/stripe/sync'

export const runtime = 'nodejs'

/**
 * Start a Checkout Session for a plan, identified by its stable lookup key
 * (e.g. "pro_monthly"). POST { "lookupKey": "pro_monthly" }.
 *
 * Generated by stripekit. Safe to edit.
 */
export async function POST(request: Request): Promise<Response> {
  const userId = await getUserId(request)
  if (!userId) return new Response('Unauthorized', { status: 401 })

  const { lookupKey } = (await request.json().catch(() => ({}))) as { lookupKey?: string }
  if (!lookupKey) return new Response('Missing lookupKey', { status: 400 })

  // Resolve the stable lookup key to a concrete price. Checkout needs a price id,
  // and price ids churn when you re-price — the lookup key is what stays stable.
  const prices = await stripe.prices.list({ lookup_keys: [lookupKey], active: true, limit: 1 })
  const price = prices.data[0]
  if (!price) return new Response(`No active price for lookup key "${lookupKey}"`, { status: 400 })

  // Eager customer: always pass an existing customer so Checkout never creates a
  // duplicate we can't map back to the user.
  const customerId = await getOrCreateCustomerId(userId)

  // Stripe requires absolute URLs. Prefer the server-configured base URL over the
  // client-supplied Origin header (which is untrusted), and fail loudly if neither
  // is a valid absolute URL rather than sending Stripe a relative one.
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? request.headers.get('origin')
  if (!baseUrl || !/^https?:\/\//.test(baseUrl)) {
    return new Response('NEXT_PUBLIC_APP_URL is not configured', { status: 500 })
  }

  const session = await stripe.checkout.sessions.create({
    customer: customerId,
    mode: price.recurring ? 'subscription' : 'payment',
    line_items: [{ price: price.id, quantity: 1 }],
    success_url: `${baseUrl}/billing?checkout=success`,
    cancel_url: `${baseUrl}/billing?checkout=cancelled`,
  })

  return Response.json({ url: session.url })
}
