import { getUserId } from '@/lib/stripe/auth'
import { stripe } from '@/lib/stripe/client'
import { store } from '@/lib/stripe/store'

export const runtime = 'nodejs'

/**
 * Open the Stripe customer portal for the current user. We pass the portal
 * configuration stripekit manages (STRIPE_PORTAL_CONFIGURATION_ID) explicitly,
 * since an API-created configuration can't be the account default.
 *
 * Generated by stripekit. Safe to edit.
 */
export async function POST(request: Request): Promise<Response> {
  const userId = await getUserId(request)
  if (!userId) return new Response('Unauthorized', { status: 401 })

  const customerId = await store.getCustomerIdByUser(userId)
  if (!customerId) return new Response('No billing account for this user', { status: 400 })

  // Stripe requires an absolute return_url. Prefer the server-configured base URL
  // over the untrusted Origin header, and fail fast if neither is absolute.
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? request.headers.get('origin')
  if (!baseUrl || !/^https?:\/\//.test(baseUrl)) {
    return new Response('NEXT_PUBLIC_APP_URL is not configured', { status: 500 })
  }
  const configuration = process.env.STRIPE_PORTAL_CONFIGURATION_ID

  const session = await stripe.billingPortal.sessions.create({
    customer: customerId,
    return_url: `${baseUrl}/billing`,
    ...(configuration ? { configuration } : {}),
  })

  return Response.json({ url: session.url })
}
