import 'server-only'
import { auth } from '@clerk/nextjs/server'

/**
 * Resolve the current user's id for billing routes (Clerk).
 * Requires clerkMiddleware() to be configured (Clerk's quickstart sets this up).
 *
 * Generated by stripekit. Safe to edit.
 */
export async function getUserId(_request: Request): Promise<string | null> {
  const { userId } = await auth()
  return userId ?? null
}
