import 'server-only'
// Adjust this import to wherever your betterAuth() instance is created
// (commonly `@/lib/auth`).
import { auth } from '@/lib/auth'

/**
 * Resolve the current user's id for billing routes (better-auth).
 * We pass the request headers straight through to avoid next/headers.
 *
 * Generated by stripekit. Safe to edit.
 */
export async function getUserId(request: Request): Promise<string | null> {
  const session = await auth.api.getSession({ headers: request.headers })
  return session?.user?.id ?? null
}
