import 'server-only'

/**
 * Resolve the current user's id for billing routes.
 *
 * TODO: stripekit couldn't detect your auth library. Implement this to return
 * the authenticated user's id (a stable string), or null if signed out. It is
 * called from the checkout and portal routes.
 *
 * Generated by stripekit — you must edit this.
 */
export async function getUserId(_request: Request): Promise<string | null> {
  throw new Error(
    'getUserId is not implemented. Edit lib/stripe/auth.ts to return the current user id.',
  )
}
