import 'server-only'
// Adjust this import to wherever your NextAuth config exports `auth`
// (commonly `@/auth` or `@/lib/auth`).
import { auth } from '@/auth'

/**
 * Resolve the current user's id for billing routes (Auth.js / NextAuth v5).
 *
 * NOTE: under the JWT strategy, `session.user.id` is NOT populated by default.
 * Add it in your NextAuth callbacks:
 *
 *   callbacks: {
 *     session({ session, token }) {
 *       if (token.sub && session.user) session.user.id = token.sub
 *       return session
 *     },
 *   }
 *
 * Generated by stripekit. Safe to edit.
 */
export async function getUserId(_request: Request): Promise<string | null> {
  const session = await auth()
  return (session?.user as { id?: string } | undefined)?.id ?? null
}
