import 'server-only'
import Stripe from 'stripe'

/**
 * The Stripe client. stripe-node pins its own API version, so we don't override
 * it. This module is server-only — the secret key must never reach the browser.
 *
 * Generated by stripekit. Safe to edit.
 */
export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  maxNetworkRetries: 2,
})
