import 'server-only'
import { store } from './store'
import type { StripeCustomerState } from './state'

/** Subscription statuses that grant access to paid features. */
const ENTITLED = new Set(['active', 'trialing'])

/**
 * Read a user's synced billing state (never hits the Stripe API).
 * Returns null if the user has no Stripe customer yet.
 *
 * Generated by stripekit. Safe to edit.
 */
export async function getCustomerState(userId: string): Promise<StripeCustomerState | null> {
  const customerId = await store.getCustomerIdByUser(userId)
  if (!customerId) return null
  return store.getState(customerId)
}

/** Whether the user currently has an entitled (active/trialing) subscription. */
export async function isSubscribed(userId: string): Promise<boolean> {
  const state = await getCustomerState(userId)
  return state !== null && state.status !== 'none' && ENTITLED.has(state.status)
}

/** The feature entitlements granted by the user's current plan (empty if unentitled). */
export async function getPlanFeatures(userId: string): Promise<Record<string, string>> {
  const state = await getCustomerState(userId)
  if (!state || state.status === 'none' || !ENTITLED.has(state.status)) return {}
  return state.features
}

/** A single feature value, or undefined. Values are strings (e.g. "5", "unlimited"). */
export async function getFeature(userId: string, feature: string): Promise<string | undefined> {
  return (await getPlanFeatures(userId))[feature]
}

/** Boolean plan gate: true when the current plan grants a truthy feature value. */
export async function hasFeature(userId: string, feature: string): Promise<boolean> {
  const value = await getFeature(userId, feature)
  return value !== undefined && value !== '' && value !== 'false' && value !== '0'
}
