import 'server-only'
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'

/**
 * Module-level singleton Drizzle client. `prepare: false` keeps it compatible
 * with transaction-pooled Postgres (PgBouncer / Supabase / Neon pooler).
 *
 * Already have a Drizzle `db` instance? Delete this file and point store.ts at
 * your existing one instead.
 *
 * Generated by stripekit. Safe to edit.
 */
const client = postgres(process.env.DATABASE_URL!, { prepare: false })
export const db = drizzle(client)
