import { sql } from 'drizzle-orm'
import { jsonb, pgTable, text } from 'drizzle-orm/pg-core'
import type { StripeCustomerState } from './state'

/**
 * Canonical mirror of Stripe billing state. `state` is a jsonb blob typed at
 * compile time (Postgres does not enforce the shape — sync.ts owns correctness).
 *
 * Generated by stripekit. Run your Drizzle migration after adding this table.
 */
export const stripeCustomers = pgTable('stripe_customers', {
  customerId: text('customer_id').primaryKey(),
  userId: text('user_id').unique(),
  state: jsonb('state')
    .$type<StripeCustomerState>()
    .notNull()
    .default(sql`'{"status":"none"}'::jsonb`),
})
