import type Stripe from 'stripe'

/**
 * The single source of truth for a customer's billing state, mirrored from
 * Stripe into your database by `syncStripeCustomerState`. Feature-gating and UI
 * read this — never the Stripe API directly in a request path.
 *
 * `status: 'none'` is the discriminant for "no subscription" (distinct from a
 * missing record); every Stripe status is a literal, so the union narrows.
 *
 * Generated by stripekit. Safe to edit.
 */
export type StripeCustomerState =
  | {
      subscriptionId: string
      /** Stripe subscription status: active, trialing, past_due, canceled, ... */
      status: Stripe.Subscription.Status
      priceId: string | null
      /** Stable lookup key (e.g. "pro_monthly") — gate features on this, not priceId. */
      lookupKey: string | null
      /** Unix seconds. Multiply by 1000 for a JS Date. */
      currentPeriodEnd: number | null
      cancelAtPeriodEnd: boolean
      /** Feature entitlements from the plan's product metadata. */
      features: Record<string, string>
      paymentMethod: { brand: string; last4: string } | null
    }
  | { status: 'none' }

/**
 * Storage contract implemented by the chosen adapter (KV, Drizzle, ...).
 * `sync.ts` depends only on this interface, never on a concrete DB client.
 */
export interface CustomerStore {
  getState(customerId: string): Promise<StripeCustomerState | null>
  setState(customerId: string, state: StripeCustomerState): Promise<void>
  getCustomerIdByUser(userId: string): Promise<string | null>
  /**
   * Atomically claim the userId -> customerId mapping. Returns the *effective*
   * customerId: the one now stored. If a concurrent call already claimed the
   * user, that winner's id is returned (and the caller should discard its own).
   */
  linkUser(userId: string, customerId: string): Promise<string>
}
