import 'server-only'
import { eq } from 'drizzle-orm'
import { db } from './db'
import { stripeCustomers } from './schema'
import type { CustomerStore } from './state'

/**
 * Drizzle (Postgres) storage adapter. A single `stripe_customers` table keyed
 * by customerId, with a unique userId and a jsonb state column. Both writes are
 * independent idempotent upserts, so the create-customer flow and out-of-order
 * webhooks can race safely.
 *
 * Generated by stripekit. Safe to edit.
 */
export const store: CustomerStore = {
  async getState(customerId) {
    const rows = await db
      .select({ state: stripeCustomers.state })
      .from(stripeCustomers)
      .where(eq(stripeCustomers.customerId, customerId))
      .limit(1)
    return rows[0]?.state ?? null
  },

  async setState(customerId, state) {
    await db
      .insert(stripeCustomers)
      .values({ customerId, state })
      .onConflictDoUpdate({ target: stripeCustomers.customerId, set: { state } })
  },

  async getCustomerIdByUser(userId) {
    const rows = await db
      .select({ customerId: stripeCustomers.customerId })
      .from(stripeCustomers)
      .where(eq(stripeCustomers.userId, userId))
      .limit(1)
    return rows[0]?.customerId ?? null
  },

  async linkUser(userId, customerId) {
    // Upsert on the unique userId. If another checkout already claimed this user,
    // the no-op update lets RETURNING hand back the existing (winning) customerId
    // instead of throwing on the unique constraint.
    const rows = await db
      .insert(stripeCustomers)
      .values({ customerId, userId, state: { status: 'none' } })
      .onConflictDoUpdate({ target: stripeCustomers.userId, set: { userId } })
      .returning({ customerId: stripeCustomers.customerId })
    return rows[0]?.customerId ?? customerId
  },
}
