import 'server-only'
import { Redis } from '@upstash/redis'
import type { CustomerStore, StripeCustomerState } from './state'

/**
 * KV storage adapter (Upstash Redis / Vercel Marketplace KV).
 * `Redis.fromEnv()` reads UPSTASH_REDIS_REST_URL + UPSTASH_REDIS_REST_TOKEN
 * (or KV_REST_API_URL + KV_REST_API_TOKEN when provisioned via Vercel).
 * @upstash/redis serializes/deserializes JSON automatically.
 *
 * Generated by stripekit. Safe to edit.
 */
const redis = Redis.fromEnv()

const stateKey = (customerId: string) => `stripe:customer:${customerId}`
const userKey = (userId: string) => `stripe:user:${userId}`

export const store: CustomerStore = {
  async getState(customerId) {
    return (await redis.get<StripeCustomerState>(stateKey(customerId))) ?? null
  },
  async setState(customerId, state) {
    await redis.set(stateKey(customerId), state)
  },
  async getCustomerIdByUser(userId) {
    return (await redis.get<string>(userKey(userId))) ?? null
  },
  async linkUser(userId, customerId) {
    // Claim the mapping only if it doesn't already exist (atomic SET NX). If a
    // concurrent checkout already claimed it, return that winner's customerId.
    const claimed = await redis.set(userKey(userId), customerId, { nx: true })
    if (claimed) return customerId
    return (await redis.get<string>(userKey(userId))) ?? customerId
  },
}
