import 'server-only'
import type Stripe from 'stripe'
import { stripe } from './client'
import { store } from './store'
import type { StripeCustomerState } from './state'

const FEATURE_PREFIX = 'stripekit_feature_'

// When a customer has more than one subscription, prefer the one that actually
// grants access. A leftover `incomplete` subscription (abandoned SCA/plan-change)
// is newer but must not mask an active one.
const STATUS_RANK: Record<string, number> = {
  active: 0,
  trialing: 1,
  past_due: 2,
  unpaid: 3,
  paused: 4,
  incomplete: 5,
  incomplete_expired: 6,
  canceled: 7,
}

/**
 * The ONLY function that writes billing state. It always refetches from Stripe
 * and overwrites the stored state, so it is idempotent and safe to call from
 * out-of-order, duplicated webhooks. Call it from every relevant webhook AND
 * from your checkout-success handler.
 *
 * Generated by stripekit. Safe to edit.
 */
export async function syncStripeCustomerState(customerId: string): Promise<StripeCustomerState> {
  const subscriptions = await stripe.subscriptions.list({
    customer: customerId,
    status: 'all',
    limit: 10,
    // Depth-4 expansion (allowed): the card is often on the customer's invoice
    // settings, not the subscription.
    expand: ['data.default_payment_method', 'data.customer'],
  })

  const subscription = pickPrimarySubscription(subscriptions.data)
  if (!subscription) {
    // Definitive "never subscribed / fully lapsed" — distinct from "not synced yet".
    const empty: StripeCustomerState = { status: 'none' }
    await store.setState(customerId, empty)
    return empty
  }

  // Since Stripe's "Basil" API version, the billing period lives on the
  // subscription ITEM, not the subscription. Reading it off the subscription
  // returns undefined — the most common copied-tutorial bug.
  const item = subscription.items.data[0]
  const price = item?.price ?? null

  const state: StripeCustomerState = {
    subscriptionId: subscription.id,
    status: subscription.status,
    priceId: price?.id ?? null,
    lookupKey: price?.lookup_key ?? null,
    currentPeriodEnd: item?.current_period_end ?? null,
    cancelAtPeriodEnd: subscription.cancel_at_period_end,
    features: await readPlanFeatures(price),
    paymentMethod: resolvePaymentMethod(subscription),
  }

  await store.setState(customerId, state)
  return state
}

/**
 * The eager-customer rule: create (or look up) the Stripe customer BEFORE
 * checkout and persist the userId <-> customerId mapping. `linkUser` is atomic,
 * so a concurrent checkout can't create two mappings; if we lose that race we
 * delete our orphaned customer and use the winner.
 */
export async function getOrCreateCustomerId(userId: string, email?: string): Promise<string> {
  const existing = await store.getCustomerIdByUser(userId)
  if (existing) return existing

  const customer = await stripe.customers.create({ email, metadata: { userId } })
  const effective = await store.linkUser(userId, customer.id)
  if (effective !== customer.id) {
    await stripe.customers.del(customer.id).catch(() => {
      /* orphan cleanup is best-effort */
    })
  }
  return effective
}

function pickPrimarySubscription(subs: Stripe.Subscription[]): Stripe.Subscription | null {
  if (subs.length === 0) return null
  return [...subs].sort((a, b) => {
    const rank = (STATUS_RANK[a.status] ?? 8) - (STATUS_RANK[b.status] ?? 8)
    return rank !== 0 ? rank : b.created - a.created // newest first within a status
  })[0]!
}

function resolvePaymentMethod(
  subscription: Stripe.Subscription,
): { brand: string; last4: string } | null {
  const customer = subscription.customer
  const customerDefault =
    typeof customer !== 'string' && !('deleted' in customer)
      ? customer.invoice_settings?.default_payment_method
      : null

  const pm = subscription.default_payment_method ?? customerDefault
  if (pm && typeof pm !== 'string' && pm.type === 'card' && pm.card) {
    return { brand: pm.card.brand, last4: pm.card.last4 }
  }
  return null
}

async function readPlanFeatures(price: Stripe.Price | null): Promise<Record<string, string>> {
  if (!price) return {}
  const productId = typeof price.product === 'string' ? price.product : price.product.id
  const product = await stripe.products.retrieve(productId)
  if (product.deleted) return {}

  const features: Record<string, string> = {}
  for (const [key, value] of Object.entries(product.metadata ?? {})) {
    if (key.startsWith(FEATURE_PREFIX)) features[key.slice(FEATURE_PREFIX.length)] = value
  }
  return features
}
